# cargo-add
# Autogenerated from man page /usr/share/man/man1/cargo-add.1.gz
complete -c cargo-add -l git
complete -c cargo-add -l branch
complete -c cargo-add -l tag
complete -c cargo-add -l rev
complete -c cargo-add -l path
complete -c cargo-add -l registry
complete -c cargo-add -l dev
complete -c cargo-add -l build
complete -c cargo-add -l target
complete -c cargo-add -l rename
complete -c cargo-add -l optional
complete -c cargo-add -l no-optional
complete -c cargo-add -l no-default-features
complete -c cargo-add -l default-features
complete -c cargo-add -l features
complete -c cargo-add -s v
complete -c cargo-add -l verbose
complete -c cargo-add -s q
complete -c cargo-add -l quiet
complete -c cargo-add -l color
complete -c cargo-add -l manifest-path
complete -c cargo-add -s h
complete -c cargo-add -l help
complete -c cargo-add -s Z

