# chezdav
# Autogenerated from man page /usr/share/man/man1/chezdav.1.gz
complete -c chezdav -s d -l htdigest -d 'Path to a htdigest file, to protect server with DIGEST method'
complete -c chezdav -s P -l path -d 'Path to export'
complete -c chezdav -s p -l port -d 'Port to listen from.  By default, a port is allocated randomly'
complete -c chezdav -s v -l verbose -d 'Verbosely print running information'
complete -c chezdav -l version -d 'Print program version number'

