# tldr
# Autogenerated from man page /usr/share/man/man1/tldr.1.gz
complete -c tldr -s v -l version -d 'show program\\(aqs version number and exit'
complete -c tldr -l search -d 'Search for a specific command from a query'
complete -c tldr -s u -l update_cache -d 'Update the local cache of pages and exit . sp Default: False'
complete -c tldr -s p -l platform -d 'Possible choices: linux, osx, sunos, windows, common '
complete -c tldr -s l -l list -d 'List all available commands for operating system . sp Default: False'
complete -c tldr -s s -l source -d 'Override the default page source . sp Default: \\(dq\\%https://raw'
complete -c tldr -s c -l color -d 'Override color stripping'
complete -c tldr -s r -l render -d 'Render local markdown files . sp Default: False'
complete -c tldr -s L -l language -d 'Override the default language'
complete -c tldr -s m -l markdown -d 'Just print the plain page file. sp Default: False'
complete -c tldr -l print-completion -d 'Possible choices: bash, zsh, tcsh . sp print shell completion script'

